### ISSUE TITLE
Multi-GPU Training 

### ISSUE THREAD

**Issue by parakh08** [TeCSAR-UNCC/EfficientHRNet#8]
While trying to Train on multiple GPU using 
`CUDA_VISIBLE_DEVICES=0,1 python tools/dist_train.py --cfg example_configs/H-2.yaml --dist-url tcp://127.0.0.1:12345 `

I get the error shown at the last but I can train on a single GPU.

Can you provide the torch and torch vision model that you used for training?

```
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f66a82b1268>
Traceback (most recent call last):
  File "/home/a0491009/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in __del__
    self._shutdown_workers()
  File "/home/a0491009/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1174, in _shutdown_workers
    if self._persistent_workers or self._workers_status[worker_id]:
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_workers_status'
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fa871b30268>
Traceback (most recent call last):
  File "/home/a0491009/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in __del__
    self._shutdown_workers()
  File "/home/a0491009/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1174, in _shutdown_workers
    if self._persistent_workers or self._workers_status[worker_id]:
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_workers_status'
Traceback (most recent call last):
  File "tools/dist_train.py", line 334, in <module>
    main()
  File "tools/dist_train.py", line 123, in main
    args=(ngpus_per_node, args, final_output_dir, tb_log_dir)
  File "/home/a0491009/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/a0491009/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/home/a0491009/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/a0491009/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/a0491009/EfficientHRNet/tools/dist_train.py", line 297, in main_worker
    final_output_dir, tb_log_dir, writer_dict, fp16=cfg.FP16.ENABLED)
  File "/home/a0491009/EfficientHRNet/tools/../lib/core/trainer.py", line 44, in do_train
    for i, (images, heatmaps, masks, joints) in enumerate(data_loader):
  File "/home/a0491009/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "/home/a0491009/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/a0491009/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 801, in __init__
    w.start()
  File "/home/a0491009/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/a0491009/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/a0491009/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/a0491009/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/a0491009/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/a0491009/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 59, in _launch
    cmd, self._fds)
  File "/home/a0491009/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/util.py", line 420, in spawnv_passfds
    False, False, None)
OSError: [Errno 12] Cannot allocate memory
```

**Comment by ghost** [comment]
Sure. My torch version in 1.8.1 and my torchvision version is 0.9.1.

But this looks like a memory issue to me. Can you monitor your RAM usage while you run distributed training? Also try with smaller batch sizes or fewer workers. Try setting your batch size to 1 and workers to 0 and seeing if you can run distributed training then. If so, you were just running out of memory and need to find the right balance for your system.

**Comment by parakh08** [comment]
Yes, you are correct, I was using the same configuration as hrnet from mmpose, but didn't monitor my ram usage. I am now able to run distributed training!
Thanks
